### ISSUE TITLE
Clean and sanitize params

### ISSUE THREAD

**Issue by camumino** [santiriera626/ruby_randimage#5]
Calling method create_and_save_file or create without params raises an exception. We should check if there are correct number of params or set a default value for them.

**Comment by santiriera626** [comment]
create_and_save_file needs at least one param.

from readme.md

Usage
Create a random svg image saved on the file system.
RubyRandimage.create_and_save_file("ruby_randimage.svg")

2.2.2 :001 > RubyRandimage.create_and_save_file
ArgumentError: wrong number of arguments (0 for 1..2)

i think that it's correct
